ENH: tracking quality module
mie-lab/trackintel pull request #140
Opened 2021-03-07 10:44 UTC by hong2223

closes #92

corresponding tests and docs are added.

2021-03-07 23:51 UTC, hong2223 commented on tests/analysis/test_tracking_quality.py
> +sys.path.append(os.path.join(os.getcwd(), "trackintel"))
I think this is not needed, will be removed in the next commit

2021-03-08 14:52 UTC, henrymartin1 requested changes
Hey, 
great addition! Finally some content for the analysis part ;-)
I have added some comments that should be addressed most of them are optional though

2021-03-08 14:52 UTC, henrymartin1 commented on trackintel/analysis/tracking_quality.py
> +
Maybe add a one-liner how the algorithm works in general:
Something like: 
Iteratively split away one day/hour from multi day/hour entries until no entry spans over multiple days/hours

2021-03-08 14:52 UTC, henrymartin1 commented on tests/analysis/test_tracking_quality.py
> +        spliited = ti.analysis.tracking_quality._split_overlaps(stps_tpls, granularity="day")
consider refactoring "spliited" to "splitted"

2021-03-09 10:29 UTC, hong2223 commented on trackintel/analysis/tracking_quality.py
> +    """
I thought one day has only 86399 sec. Apparently wrong...

2021-03-09 10:32 UTC, hong2223 commented on trackintel/analysis/tracking_quality.py
> +    df : GeoDataFrame (as trackintel datamodels)
df has to have the columns "finished_at" and "started_at" and sometimes also "day". I guess the safest is to say it should be a trackintel model. 
This function is only called inside, so I think it does not matter so much anyway.

2021-03-09 10:35 UTC, hong2223 commented on trackintel/analysis/tracking_quality.py
> +    """Split input df that have a duration of several days or hours.
Maybe this function does the job for all the users. 
What it does is basically to duplicate the entries that span several day/hour and change the time info. user_id is not just duplicated

2021-03-09 12:20 UTC, henrymartin1 commented on trackintel/analysis/tracking_quality.py
> +    df : GeoDataFrame (as trackintel datamodels)
👍

2021-03-09 12:23 UTC, henrymartin1 commented on trackintel/analysis/tracking_quality.py
> +    """Split input df that have a duration of several days or hours.
Yes, I think you are right.

2021-03-09 21:17 UTC, hong2223 commented on trackintel/analysis/tracking_quality.py
> +        extent = 60 * 60 * 24 - 1
grouping by day is unique -> multiple days would not exist in one df; theoretical upper limit is just `sec_of_day`
grouping by hour is not unique -> it is possible that entries from different days are grouped into the same hour df; the tracked_duration thus has a theoretical upper limit of `sec_of_hour * unique_days`

2021-03-09 22:19 UTC, hong2223 commented
The comments shall be fixed and additional tests are added.

2021-03-12 21:42 UTC, henrymartin1 commented
Nice contribution. This is really super useful, I think I can directly use it 👍

2021-03-12 21:42 UTC, merged