ENH: tracking_quality function
mie-lab/trackintel pull request #221
Opened 2021-05-23 10:06 UTC by hong2223

Two enhancements for the `tracking_quality()`/`_split_overlaps()` function:
- previously `_split_overlaps` split records that span several days in midnight, e.g., a record that span 2 days is split into _started_at - 23:59:59_ and _00:00:00 - finished_at_, which means 1 second is lost whenever we perform a split. Now this is changed into _started_at - 00:00:00_ and _00:00:00 - finished_at_. Tests are changed accordingly.
- previously `_split_overlaps` did not deal with `duration` column. Now, this column is updated in the function.

2021-06-04 21:23 UTC, henrymartin1 requested changes
Nice fix. I have some minor comments to address.

2021-06-04 21:23 UTC, henrymartin1 commented on tests/analysis/test_tracking_quality.py
> +        """Test if _split_overlaps() function can split records that span several days."""
I think the docstring is wrong

2021-06-05 15:25 UTC, hong2223 commented on tests/analysis/test_tracking_quality.py
> +    def test_accessors(self):
the accessor testing is splitted into 3 functions

2021-06-10 22:29 UTC, henrymartin1 approved these changes
Great work, sorry that I missed this one.

2021-06-10 22:29 UTC, merged