cluster_staypoints: add support for big data
mie-lab/trackintel pull request #62
Opened 2020-11-19 23:16 UTC by hong2223

- change the cluster_staypoints function: the DBSCAN now directly accepts the distance metric and does not use a pre-calculated pairwise distance matrix.
- add test for haversine distance DBSCAN
- update author information

2020-11-19 23:17 UTC, hong2223 commented
I am not sure if I should add my name in the **copyright**, please check

2020-11-21 16:45 UTC, henrymartin1 requested changes
address comments before merging

2020-11-21 17:06 UTC, henrymartin1 commented
> 
> 
> address comments before merging

(This concerns only the comment about the epsilon, the others are rather general...)

2020-11-22 11:38 UTC, hong2223 commented on trackintel/preprocessing/staypoints.py
> +        db = DBSCAN(eps=epsilon, min_samples=num_samples, algorithm='ball_tree', metric=distance_matrix_metric)
the R-tree method does not support 'haversine' distance calculation

2020-11-22 16:00 UTC, hong2223 commented on trackintel/preprocessing/staypoints.py
> +        if distance_matrix_metric == 'haversine':
the input and output of scikit-learn’s haversine metric are both in radian units, see [clustering example](https://geoffboeing.com/2014/08/clustering-to-reduce-spatial-data-set-size/) and our [own code example ](https://github.com/mie-lab/trackintel/blob/master/tests/geogr/test_distances.py). The `epsilon` here is directly applied to the metric output, thus needs to be in radian.

2020-11-22 16:07 UTC, hong2223 commented on trackintel/preprocessing/staypoints.py
> +                    p = np.array([[radians(g.y), radians(g.x)] for g in user_staypoints.geometry])
comments added

2020-11-22 16:34 UTC, henrymartin1 approved these changes

2020-11-22 16:35 UTC, henrymartin1 commented
Nice! Thanks for the clarification.

2020-11-22 16:35 UTC, merged